package ar.edu.itba.genetic_algorithms.algorithms.crossover_methods;

import ar.edu.itba.genetic_algorithms.algorithms.IndividualPair;

public interface CrossoverMethod {

    /**
     * Crosses two individuals, generating two new ones.
     *
     * @param parents pair of individuals that will be crossed.
     * @return new pair of individuals generated by the crossover.
     */
    IndividualPair crossover(IndividualPair parents);

}
