package ar.edu.itba.genetic_algorithms.algorithms.crossover_methods;

import ar.edu.itba.genetic_algorithms.algorithms.ChromosomePair;

public interface CrossoverMethod {

    /**
     * Crosses two chromosomes, generating two new ones.
     *
     * @param parents pair of chromosomes that will be crossed.
     * @return new pair of chromosomes generated by the crossover.
     */
    ChromosomePair crossover(ChromosomePair parents);

}
